/* ═══════════════════════════════════════════
   Mama Minds — Language Translations
   All 11 official South African languages
   ═══════════════════════════════════════════ */

export const LANGUAGES = {
  en: {
    name: 'English', chip: 'EN', native: 'English',
    greeting: 'Good morning,', offline: 'Offline ready',
    checkin_label: 'Days since last check-in', checkin_hint: 'Take today\'s mood check',
    alert_title: 'Alert your support network', alert_sub: 'Reach a healthcare worker or loved one',
    mood_label: 'How are you feeling today?',
    tools_label: 'Tools & support', progress_label: 'Recent progress', last_score: 'Last EPDS score',
    card_assess: 'EPDS Assessment', card_assess_sub: '10-question check',
    card_resources: 'Resources', card_resources_sub: 'Guides & support',
    card_help: 'Get help now', card_help_sub: 'Alert support',
    card_profile: 'My profile', card_profile_sub: 'Settings & plan',
    moods: ['Low', 'Okay', 'Good', 'Joyful'],
    nav: ['Home', 'Check-in', 'Resources', 'Alert'],
    assess_title: 'EPDS Assessment', assess_sub: 'Edinburgh Postnatal Depression Scale',
    q_of: 'Question {n} of 10', btn_next: 'Next', btn_results: 'See my results', btn_back: 'Back',
    result_label: 'Your EPDS score', result_means: 'What this means', result_steps: 'Recommended next steps',
    result_btn_alert: 'Alert my support network', result_btn_resources: 'View support resources', result_btn_retake: 'Take assessment again',
    result_categories: { low: 'Low concern', mid: 'Mild to moderate', high: 'High concern' },
    result_meanings: {
      low: 'Your score suggests you may be managing well right now. Continue with daily mood tracking and share your score with your midwife or health worker at your next visit.',
      mid: 'Your score suggests you may be experiencing some symptoms of postnatal depression. This is common and treatable — please speak to a community health worker or clinic nurse soon.',
      high: 'Your score is elevated and suggests you may need additional support right now. Please know this is not your fault — help is available. Reach out to a healthcare provider as soon as possible.'
    },
    result_steps_text: {
      low: 'Continue daily mood check-ins. Share your score with your health worker at your next visit. Keep using the coping tools in Resources.',
      mid: 'Speak to a CHW or clinic nurse within the next few days. Try the breathing exercises in Resources. Consider joining a peer support group.',
      high: 'Contact a healthcare provider today. Use the Alert button to reach your support network now. You deserve care and support — please do not wait.'
    },
    resources_title: 'Support Resources', resources_sub: 'Available offline — no internet needed',
    res_tabs: ['Understanding PPD', 'Coping Tools', 'Family & Community', 'Helplines', 'Healthcare'],
    alert_screen_title: 'Alert my support network', alert_screen_sub: 'Send a message to your healthcare provider or loved ones',
    send_btn: 'Send alert now', send_hint: 'Works without internet via SMS fallback',
    default_message: 'I\'m struggling with my mental health right now. Please check in on me when you can. — Sent from Mama Minds',
    profile_title: 'My profile', plan_label: 'Current plan', plan_free: 'Basic (Free)',
    language_label: 'Language', location_label: 'Location', offline_label: 'Offline mode',
    last_assess_label: 'Last assessment', delete_data: 'Delete my data',
    upgrade_title: 'Mama Minds Plus',
    upgrade_desc: 'Unlimited assessments, tele-health session booking, private therapist chat, full care plan export, and priority emergency alerts. R89/month or R799/year.',
    upgrade_btn: 'Upgrade to Plus'
  },

  zu: {
    name: 'Zulu', chip: 'ZU', native: 'isiZulu',
    greeting: 'Sawubona,', offline: 'Isebenza ngaphandle kwe-inthanethi',
    checkin_label: 'Izinsuku kusukela ekuhlolweni kwakho', checkin_hint: 'Hlola umzwelo wakho namhlanje',
    alert_title: 'Xwayisa inethiwekhi yakho yokusekela', alert_sub: 'Shayela umsizi wezempilo noma othandiweyo',
    mood_label: 'Uzizwa kanjani namhlanje?',
    tools_label: 'Amathuluzi & ukusekela', progress_label: 'Inqubekela phambili yamanje', last_score: 'Amapointi e-EPDS ekugcineni',
    card_assess: 'Ukuhlolwa kwe-EPDS', card_assess_sub: 'Imibuzo eyishumi',
    card_resources: 'Izinsiza', card_resources_sub: 'Izikhungo & ukusekela',
    card_help: 'Thola usizo manje', card_help_sub: 'Xwayisa ukusekela',
    card_profile: 'Iphrofayili yami', card_profile_sub: 'Izilungiselelo & iplanhi',
    moods: ['Phansi', 'Kulungile', 'Kuhle', 'Ujabule'],
    nav: ['Ikhaya', 'Hlola', 'Izinsiza', 'Xwayisa'],
    assess_title: 'Ukuhlolwa kwe-EPDS', assess_sub: 'Isilinganiso se-Edinburgh Sokukhathazeka Ngemuva Kokubeletha',
    q_of: 'Umbuzo {n} we-10', btn_next: 'Okulandelayo', btn_results: 'Bona imiphumela yami', btn_back: 'Emuva',
    result_label: 'Amapointi akho e-EPDS', result_means: 'Lokhu kusho ukuthini', result_steps: 'Izinyathelo ezilandelayo ezihlongoswayo',
    result_btn_alert: 'Xwayisa inethiwekhi yami yokusekela', result_btn_resources: 'Buka izinsiza zokusekela', result_btn_retake: 'Phinda ukuhlolwa',
    result_categories: { low: 'Ukukhathazeka okuphansi', mid: 'Okupakathi', high: 'Ukukhathazeka okukhulu' },
    result_meanings: {
      low: 'Amapointi akho asikho ephezulu. Qhubeka nokullandela imizwelo yakho nsuku zonke futhi wabelane namapointi akho nomsizi wezempilo kwiviziti yakho elandelayo.',
      mid: 'Amapointi akho abonakalisa ukuthi ungase ubekhathazeke ngemuva kokubeletha. Lokhu kuvamile futhi kulashwa — xoxa nochwepheshe wezempilo maduze.',
      high: 'Amapointi akho aphezulu. Ngicela uxhumane nomhlinzeki wezempilo namhlanje. Lokhu akusona isono sakho — usizo luyatholakala.'
    },
    result_steps_text: {
      low: 'Qhubeka nohlolo lwemizwelo nsuku zonke. Xoxa ngamapointi akho nomsizi wezempilo.',
      mid: 'Xoxa nochwepheshe wezempilo ezinsukwini ezimbalwa. Zama imisebenzi yokuphefumula.',
      high: 'Xhumana nomhlinzeki wezempilo namhlanje. Sebenzisa inkinobho Yexwayiso.'
    },
    resources_title: 'Izinsiza Zokusekela', resources_sub: 'Iyatholakala ngaphandle kwe-inthanethi',
    res_tabs: ['Ukuqonda i-PPD', 'Amathuluzi', 'Umndeni & Umphakathi', 'Izinombolo Zosizo', 'Ukunakekelwa Kwezempilo'],
    alert_screen_title: 'Xwayisa inethiwekhi yami yokusekela', alert_screen_sub: 'Thumela umyalezo kumhlinzeki wezempilo noma othandiweyo',
    send_btn: 'Thumela isixwayiso manje', send_hint: 'Isebenza ngaphandle kwe-inthanethi nge-SMS',
    default_message: 'Ngikhathazekile ngezempilo yami yengqondo njengamanje. Ngicela uhlole ukuthi nginjani. — Kuthunywe ku-Mama Minds',
    profile_title: 'Iphrofayili yami', plan_label: 'Iplanhi yamanje', plan_free: 'Eyisisekelo (Mahhala)',
    language_label: 'Ulimi', location_label: 'Indawo', offline_label: 'Imodi ye-offline',
    last_assess_label: 'Ukuhlolwa okokugcina', delete_data: 'Susa idatha yami',
    upgrade_title: 'Mama Minds Plus',
    upgrade_desc: 'Ukuhlolwa okungakhawuliwe, ukubhukha ithele-mpilo, ingxoxo yomhleli wezengqondo oyimfihlo, nokukhushulwa kohlelo lokukhathalela. R89/inyanga noma R799/unyaka.',
    upgrade_btn: 'Khushulelana ku-Plus'
  },

  xh: {
    name: 'Xhosa', chip: 'XH', native: 'isiXhosa',
    greeting: 'Molo,', offline: 'Isebenza ngaphandle kwe-intanethi',
    checkin_label: 'Iintsuku ukusukela kucheki lwakho', checkin_hint: 'Thabatha ukuzihlola kwakho kwemood namhlanje',
    alert_title: 'Xela unxibelelwano lwakho lwenkxaso', alert_sub: 'Fikelela usebenzisi wezempilo okanye umntu omthandayo',
    mood_label: 'Uziva njani namhlanje?',
    tools_label: 'Izixhobo & inkxaso', progress_label: 'Inkqubela phambili yakutsha nje', last_score: 'Isikolo sakho se-EPDS esidlulileyo',
    card_assess: 'Uvavanyo lwe-EPDS', card_assess_sub: 'Imibuzo elishumi',
    card_resources: 'Izixhobo', card_resources_sub: 'Izikhokelo & inkxaso',
    card_help: 'Fumana uncedo ngoku', card_help_sub: 'Xela inkxaso',
    card_profile: 'Iprofayile yam', card_profile_sub: 'Iisetingi & isicwangciso',
    moods: ['Phantsi', 'Kulungile', 'Kulungile', 'Wonelisekile'],
    nav: ['Ikhaya', 'Jonga', 'Izixhobo', 'Xela'],
    assess_title: 'Uvavanyo lwe-EPDS', assess_sub: 'Isilinganiso se-Edinburgh sokukhathazeka emva kwe-postpartum',
    q_of: 'Umbuzo {n} we-10', btn_next: 'Okulandelayo', btn_results: 'Jonga iziphumo zam', btn_back: 'Emva',
    result_label: 'Isikolo sakho se-EPDS', result_means: 'Oku kuthetha ntoni', result_steps: 'Amanyathelo alandelayo acetywayo',
    result_btn_alert: 'Xela unxibelelwano lwam lwenkxaso', result_btn_resources: 'Jonga izixhobo zenkxaso', result_btn_retake: 'Yenza uvavanyo kwakhona',
    result_categories: { low: 'Uxinzelelo oluncinane', mid: 'Phakathi', high: 'Uxinzelelo oluphezulu' },
    result_meanings: {
      low: 'Isikolo sakho asiphezulu. Qhubeka nokulandelela imood yakho yonke imihla.',
      mid: 'Isikolo sakho sibonisa ukuba ungaziva nzima emva kokuzala. Thetha nomsebenzi wezempilo ngokukhawuleza.',
      high: 'Isikolo sakho siphezulu. Nceda uqhagamshelane nomhlinzeki wezempilo namhlanje.'
    },
    result_steps_text: {
      low: 'Qhubeka nocheki lwemood yonke imihla. Yabelana ngesikolo sakho nomsebenzi wezempilo.',
      mid: 'Thetha nochwepheshe wezempilo kwiiintsuku ezimbalwa. Zama imisebenzi yokuphefumla.',
      high: 'Qhagamshelana nomhlinzeki wezempilo namhlanje. Sebenzisa iqhosha leSilumkiso.'
    },
    resources_title: 'Izixhobo Zenkxaso', resources_sub: 'Iyafumaneka ngaphandle kwe-intanethi',
    res_tabs: ['Qonda i-PPD', 'Izixhobo', 'Usapho & Uluntu', 'Iinombolo Zoncedo', 'Ezempilo'],
    alert_screen_title: 'Xela unxibelelwano lwam lwenkxaso', alert_screen_sub: 'Thumela umyalezo kumhlinzeki wezempilo okanye umntu omthandayo',
    send_btn: 'Thumela isaziso ngoku', send_hint: 'Isebenza ngaphandle kwe-intanethi nge-SMS',
    default_message: 'Ndixabana nempilo yam yengqondo ngoku. Nceda undijongele. — Ithunyelwe kwi-Mama Minds',
    profile_title: 'Iprofayile yam', plan_label: 'Isicwangciso sangoku', plan_free: 'Esisisiseko (Simahla)',
    language_label: 'Ulwimi', location_label: 'Indawo', offline_label: 'Imowudi ye-offline',
    last_assess_label: 'Uvavanyo lwamva nje', delete_data: 'Cima idatha yam',
    upgrade_title: 'Mama Minds Plus',
    upgrade_desc: 'Uvavanyo olungaphelelanga, ukubhukha i-tele-health, ingxoxo yomhleli wengqondo oyimfihlo. R89/inyanga okanye R799/unyaka.',
    upgrade_btn: 'Nyuka uye kwi-Plus'
  },

  af: {
    name: 'Afrikaans', chip: 'AF', native: 'Afrikaans',
    greeting: 'Goeie môre,', offline: 'Werk sonder internet',
    checkin_label: 'Dae sedert jou laaste inskrywing', checkin_hint: 'Doen vandag se gemoedskontrole',
    alert_title: 'Waarsku jou ondersteuningsnetwerk', alert_sub: 'Bereik \'n gesondheidswerker of geliefde',
    mood_label: 'Hoe voel jy vandag?',
    tools_label: 'Gereedskap en ondersteuning', progress_label: 'Onlangse vordering', last_score: 'Laaste EPDS-telling',
    card_assess: 'EPDS-assessering', card_assess_sub: '10 vrae',
    card_resources: 'Hulpbronne', card_resources_sub: 'Gidse en ondersteuning',
    card_help: 'Kry nou hulp', card_help_sub: 'Waarsku ondersteuning',
    card_profile: 'My profiel', card_profile_sub: 'Instellings en plan',
    moods: ['Neerslagtig', 'Okay', 'Goed', 'Bly'],
    nav: ['Tuis', 'Inskrywing', 'Hulpbronne', 'Waarsku'],
    assess_title: 'EPDS-assessering', assess_sub: 'Edinburgh Postnatale Depressie-skaal',
    q_of: 'Vraag {n} van 10', btn_next: 'Volgende', btn_results: 'Sien my resultate', btn_back: 'Terug',
    result_label: 'Jou EPDS-telling', result_means: 'Wat dit beteken', result_steps: 'Aanbevole volgende stappe',
    result_btn_alert: 'Waarsku my ondersteuningsnetwerk', result_btn_resources: 'Bekyk ondersteuningshulpbronne', result_btn_retake: 'Doen assessering weer',
    result_categories: { low: 'Lae risiko', mid: 'Matige risiko', high: 'Hoë risiko' },
    result_meanings: {
      low: 'Jou telling dui aan dat jy dalk goed bestuur. Gaan voort met daaglikse stemming-opsporing en deel jou telling met jou gesondheidswerker.',
      mid: 'Jou telling dui aan dat jy moontlik simptome van postnatale depressie ervaar. Dit is behandelbaar — praat binnekort met \'n gesondheidswerker.',
      high: 'Jou telling is hoog. Kontak asseblief \'n gesondheidsverskaffer so gou as moontlik. Jy verdien ondersteuning.'
    },
    result_steps_text: {
      low: 'Gaan voort met daaglikse gemoedsopsporing. Deel jou telling met jou gesondheidswerker.',
      mid: 'Praat binne die volgende paar dae met \'n gemeenskapsgesondheidswerker.',
      high: 'Kontak \'n gesondheidsverskaffer vandag. Gebruik die waarskuwingsknoppie.'
    },
    resources_title: 'Ondersteuningshulpbronne', resources_sub: 'Beskikbaar sonder internet',
    res_tabs: ['Verstaan PPD', 'Hanterings gereedskap', 'Familie & Gemeenskap', 'Hulplyne', 'Gesondheidsorg'],
    alert_screen_title: 'Waarsku my ondersteuningsnetwerk', alert_screen_sub: 'Stuur \'n boodskap aan jou gesondheidsorgverskaffer of geliefde',
    send_btn: 'Stuur waarskuwing nou', send_hint: 'Werk sonder internet via SMS',
    default_message: 'Ek sukkel tans met my geestesgesondheid. Gaan asseblief na hoe dit met my gaan. — Gestuur van Mama Minds',
    profile_title: 'My profiel', plan_label: 'Huidige plan', plan_free: 'Basies (Gratis)',
    language_label: 'Taal', location_label: 'Ligging', offline_label: 'Vanlyn-modus',
    last_assess_label: 'Laaste assessering', delete_data: 'Vee my data uit',
    upgrade_title: 'Mama Minds Plus',
    upgrade_desc: 'Onbeperkte assesserings, tele-gesondheid besprekings, privaat terapeut-geselsie. R89/maand of R799/jaar.',
    upgrade_btn: 'Opgradeer na Plus'
  },

  st: {
    name: 'Sesotho', chip: 'ST', native: 'Sesotho',
    greeting: 'Lumela,', offline: 'E sebetsa ntle le marang-rang',
    checkin_label: 'Matsatsi ho tloha tekong ea hao', checkin_hint: 'Nka tekolo ea maikutlo a kajeno',
    alert_title: 'Tsebisa marang-rang a hao a tšehetso', alert_sub: 'Fihlella mosebetsi oa tsa bophelo kapa motho oa hao o ratoang',
    mood_label: 'O ikutloa joang kajeno?',
    tools_label: 'Lisebelisoa le tšehetso', progress_label: 'Tsoelo-pele ea morao tjena', last_score: 'Manane a EPDS a ho qetela',
    card_assess: 'Tekolo ea EPDS', card_assess_sub: 'Lipotso tse 10',
    card_resources: 'Mehloli', card_resources_sub: 'Likhokahano & tšehetso',
    card_help: 'Fumana thuso joale', card_help_sub: 'Tsebisa tšehetso',
    card_profile: 'Profaele ea ka', card_profile_sub: 'Litlhophiso & moralo',
    moods: ['Fatše', 'Ho lokile', 'Hantle', 'Thabile'],
    nav: ['Lapeng', 'Beha leihlo', 'Mehloli', 'Tsebisa'],
    assess_title: 'Tekolo ea EPDS', assess_sub: 'Tekanyo ea Edinburgh ea Ho Hiloa ka mor\'a Tsoalo',
    q_of: 'Potso {n} ea 10', btn_next: 'E latelang', btn_results: 'Bona liphetho tsa ka', btn_back: 'Morao',
    result_label: 'Manane a hao a EPDS', result_means: 'Se sena se bolela eng', result_steps: 'Mehato e hlokometsoeng e latelang',
    result_btn_alert: 'Tsebisa marang-rang a ka a tšehetso', result_btn_resources: 'Sheba mehloli ea tšehetso', result_btn_retake: 'Nka tekolo hape',
    result_categories: { low: 'Kotsi e tlase', mid: 'Kateng', high: 'Kotsi e phahameng' },
    result_meanings: {
      low: 'Manane a hao ha a phahamang. Tsoela pele ho hlahloba maikutlo a hao letsatsi le leng le le leng.',
      mid: 'Manane a hao a bontša hore o ka ba le matšoao a ho hiloa ha mor\'a tsoalo. Bua le mosebetsi oa tsa bophelo kapele.',
      high: 'Manane a hao a phahame. Ka kopo ikopanye le mohaki oa tsa bophelo kajeno.'
    },
    result_steps_text: {
      low: 'Tsoela pele ho hlahloba maikutlo tsatsi le leng le le leng. Arolelana manane a hao le mosebetsi oa tsa bophelo.',
      mid: 'Bua le chwepheshe oa tsa bophelo matsatsing a mmaloa a latelang.',
      high: 'Ikopanye le mohaki oa tsa bophelo kajeno. Sebelisa konope ea Tsebiso.'
    },
    resources_title: 'Mehloli ea Tšehetso', resources_sub: 'E fumaneha ntle le marang-rang',
    res_tabs: ['Utloa PPD', 'Lisebelisoa', 'Lelapa & Sechaba', 'Linomoro tsa Thuso', 'Tlhokomelo ea Bophelo'],
    alert_screen_title: 'Tsebisa marang-rang a ka a tšehetso', alert_screen_sub: 'Romela molaetsa ho mohaki oa tsa bophelo kapa motho o ratoang',
    send_btn: 'Romela tsebiso joale', send_hint: 'E sebetsa ntle le marang-rang ka SMS',
    default_message: 'Ke na le mathata a bophelo ba ka ba kelello hona joale. Ke kopa u hlahlobe hore ke teng. — Ho rometswe ho tsoa ho Mama Minds',
    profile_title: 'Profaele ea ka', plan_label: 'Moralo oa hona joale', plan_free: 'Motheo (Mahala)',
    language_label: 'Puo', location_label: 'Sebaka', offline_label: 'Mokhoa oa ho se be marang-rang',
    last_assess_label: 'Tekolo ea ho qetela', delete_data: 'Hlakola data ea ka',
    upgrade_title: 'Mama Minds Plus',
    upgrade_desc: 'Tekolo e sa lekaneng, ho bukhisa sesene sa tele-bophelo, ingxoxo ya mohlophisi wa ingqondo. R89/kgwedi kapa R799/selemo.',
    upgrade_btn: 'Eketsa ho Plus'
  },

  tn: {
    name: 'Setswana', chip: 'TN', native: 'Setswana',
    greeting: 'Dumela,', offline: 'E dira ntle le inthanete',
    checkin_label: 'Matsatsi go tswa go lebelo la gago la bofelo', checkin_hint: 'Tsaya go lekola maikutlo a gago a letsatsi',
    alert_title: 'Itsise kgokagano ya gago ya thuso', alert_sub: 'Fitlhelela mooki wa bophelo kgotsa motho yo o ratwang',
    mood_label: 'O ikutlwa jang gompieno?',
    tools_label: 'Didirisiwa le thuso', progress_label: 'Ntlhatloso ya monaganelo', last_score: 'Palo ya gago ya EPDS ya bofelo',
    card_assess: 'Tekolo ya EPDS', card_assess_sub: 'Dipotso di le 10',
    card_resources: 'Didirisiwa', card_resources_sub: 'Dikgokagano & thuso',
    card_help: 'Bona thuso jaanong', card_help_sub: 'Itsise thuso',
    card_profile: 'Profaele ya me', card_profile_sub: 'Dipeelo & moralo',
    moods: ['Tlase', 'Go siame', 'Botoka', 'Thabile'],
    nav: ['Gae', 'Leba', 'Didirisiwa', 'Itsise'],
    assess_title: 'Tekolo ya EPDS', assess_sub: 'Tekanyetso ya Edinburgh ya Phôlô ya Morago ga Pelego',
    q_of: 'Potso {n} ya 10', btn_next: 'E e latelang', btn_results: 'Bona dipholo tsa me', btn_back: 'Morago',
    result_label: 'Palo ya gago ya EPDS', result_means: 'Se se kaya eng', result_steps: 'Magato a a akantsweng a a latelang',
    result_btn_alert: 'Itsise kgokagano ya me ya thuso', result_btn_resources: 'Bona didirisiwa tsa thuso', result_btn_retake: 'Tsaya tekolo gape',
    result_categories: { low: 'Kotsi e eseng kwa godimo', mid: 'Magareng', high: 'Kotsi e phagameng' },
    result_meanings: {
      low: 'Palo ya gago ga e phagamile. Tswelela go lekola maikutlo a gago letsatsi leng le leng.',
      mid: 'Palo ya gago e bontsha gore o ka nna o na le matshwao a phôlô ya morago ga pelego. Bua le mooki wa bophelo ka bonako.',
      high: 'Palo ya gago e phagame. Ka kopo ikopanye le mooki wa bophelo gompieno.'
    },
    result_steps_text: {
      low: 'Tswelela go lekola maikutlo letsatsi leng le leng. Abelana palo ya gago le mooki wa gago wa bophelo.',
      mid: 'Bua le setsebi sa bophelo mo malatsing a mmalwa a a latelang.',
      high: 'Ikopanye le mooki wa bophelo gompieno. Dirisa konopo ya Itsisa.'
    },
    resources_title: 'Didirisiwa tsa Thuso', resources_sub: 'E fitlhelwa ntle le inthanete',
    res_tabs: ['Tlhaloganya PPD', 'Didirisiwa', 'Lelapa & Setshaba', 'Dinomoro tsa Thuso', 'Tlhokomelo ya Bophelo'],
    alert_screen_title: 'Itsise kgokagano ya me ya thuso', alert_screen_sub: 'Romela molaetsa go mooki wa bophelo kgotsa motho yo o ratwang',
    send_btn: 'Romela itsiso jaanong', send_hint: 'E dira ntle le inthanete ka SMS',
    default_message: 'Ke na le mathata a bophelo jwa me jwa kelelo jaanong. Ka kopo tlhokomela gore ke teng. — E romelwa go tswa go Mama Minds',
    profile_title: 'Profaele ya me', plan_label: 'Moralo wa jaanong', plan_free: 'Motheo (Mahala)',
    language_label: 'Puo', location_label: 'Sebaka', offline_label: 'Mokgwa wa go se na inthanete',
    last_assess_label: 'Tekolo ya bofelo', delete_data: 'Phimola data ya me',
    upgrade_title: 'Mama Minds Plus',
    upgrade_desc: 'Tekolo e e sa lekaneng, go bukhisa sesene sa tele-bophelo, ingxoxo ya mohlophisi wa kelelo. R89/kgwedi kgotsa R799/ngwaga.',
    upgrade_btn: 'Tokafatsa go Plus'
  },

  nso: {
    name: 'Sepedi', chip: 'NSO', native: 'Sepedi',
    greeting: 'Dumela,', offline: 'E šoma ntle le inthanete',
    checkin_label: 'Matsatsi go tšwa go tlhatlhobong ya gago ya mafelelo', checkin_hint: 'Tšea go hlola maikutlo a gago a lehono',
    alert_title: 'Tsebišša kgokagano ya gago ya thušo', alert_sub: 'Fihlela mooki wa bophelo kgotša motho yo o ratwago',
    mood_label: 'O ikutlwa bjang lehono?',
    tools_label: 'Didirišwa le thušo', progress_label: 'Katlego ya monaganelo', last_score: 'Palo ya gago ya EPDS ya mafelelo',
    card_assess: 'Tlhatlhobo ya EPDS', card_assess_sub: 'Dipotšo tše 10',
    card_resources: 'Didirišwa', card_resources_sub: 'Dikgokagano & thušo',
    card_help: 'Hwetša thušo bjale', card_help_sub: 'Tsebišša thušo',
    card_profile: 'Profaele ya ka', card_profile_sub: 'Dipeelo & moralo',
    moods: ['Fase', 'Go lokile', 'Botse', 'Thabile'],
    nav: ['Gae', 'Lebelela', 'Didirišwa', 'Tsebišša'],
    assess_title: 'Tlhatlhobo ya EPDS', assess_sub: 'Tekanyo ya Edinburgh ya Pholo ya Morago ga Tswalo',
    q_of: 'Potšo {n} ya 10', btn_next: 'E latelago', btn_results: 'Bona diphetho tša ka', btn_back: 'Morago',
    result_label: 'Palo ya gago ya EPDS', result_means: 'Se se ra eng', result_steps: 'Magato a a šišintšwego a a latelago',
    result_btn_alert: 'Tsebišša kgokagano ya ka ya thušo', result_btn_resources: 'Bona didirišwa tša thušo', result_btn_retake: 'Tšea tlhatlhobo gape',
    result_categories: { low: 'Kotsi ye nnyane', mid: 'Gare', high: 'Kotsi ye phagameng' },
    result_meanings: {
      low: 'Palo ya gago ga e phagamile. Tšwela pele go hlola maikutlo a gago ka mehla.',
      mid: 'Palo ya gago e bontšha gore o ka ba le matšhwao a pholo ya morago ga tswalo. Bolela le mooki wa bophelo ka pela.',
      high: 'Palo ya gago e phagame. Hle ikopanye le mooki wa bophelo lehono.'
    },
    result_steps_text: {
      low: 'Tšwela pele go hlola maikutlo ka mehla. Abelana palo ya gago le mooki wa bophelo.',
      mid: 'Bolela le setsebi sa bophelo ka matšatšing a mmalwa a latelago.',
      high: 'Ikopanye le mooki wa bophelo lehono. Diriša konopo ya Tsebišša.'
    },
    resources_title: 'Didirišwa tša Thušo', resources_sub: 'E hwetšagala ntle le inthanete',
    res_tabs: ['Kwešiša PPD', 'Didirišwa', 'Leloko & Setšhaba', 'Dinomoro tša Thušo', 'Tlhokomelo ya Bophelo'],
    alert_screen_title: 'Tsebišša kgokagano ya ka ya thušo', alert_screen_sub: 'Romela molaetsa go mooki wa bophelo kgotša motho yo o ratwago',
    send_btn: 'Romela tsebišo bjale', send_hint: 'E šoma ntle le inthanete ka SMS',
    default_message: 'Ke na le mathata a bophelo bja ka bja kelelo bjale. Ka kopo hlola gore ke teng. — E romilwe go tswa go Mama Minds',
    profile_title: 'Profaele ya ka', plan_label: 'Moralo wa bjale', plan_free: 'Motheo (Mahala)',
    language_label: 'Puo', location_label: 'Lefelo', offline_label: 'Mokgwa wa go se na inthanete',
    last_assess_label: 'Tlhatlhobo ya mafelelo', delete_data: 'Phimola data ya ka',
    upgrade_title: 'Mama Minds Plus',
    upgrade_desc: 'Tlhatlhobo ye sa lekaneng, go bukhisa sesene sa tele-bophelo, ingxoxo ya mohlophisi wa kelelo. R89/kgwedi kgotsa R799/ngwaga.',
    upgrade_btn: 'Eketša go Plus'
  },

  ts: {
    name: 'Xitsonga', chip: 'TS', native: 'Xitsonga',
    greeting: 'Avuxeni,', offline: 'Yi tirha handle ka inthanete',
    checkin_label: 'Masiku ku sukela ku hlola ka wena ka makumu', checkin_hint: 'Teka ku hlola mimpfumawulo ya loko wa namuntlha',
    alert_title: 'Xivisa nhlangano wa wena wa pfuneto', alert_sub: 'Fikelela muhlayisi wa vulavulisi bya miri kumbe munhu wo rhandza',
    mood_label: 'U twisisa njhani namuntlha?',
    tools_label: 'Switirho ni pfuneto', progress_label: 'Nhluvuko wa nkarhi lowu hundzeke', last_score: 'Ntlawa wa wena wa EPDS wa makumu',
    card_assess: 'Hlelo ra EPDS', card_assess_sub: 'Swivutiso swa 10',
    card_resources: 'Switirho', card_resources_sub: 'Swilenge & pfuneto',
    card_help: 'Kuma pfuneto sweswi', card_help_sub: 'Xivisa pfuneto',
    card_profile: 'Profayili ya mina', card_profile_sub: 'Swirho & mupfumelelo',
    moods: ['Ehansi', 'Ku lulamile', 'Kahle', 'Tsakile'],
    nav: ['Kaya', 'Languta', 'Switirho', 'Xivisa'],
    assess_title: 'Hlelo ra EPDS', assess_sub: 'Ntlawa wa Edinburgh wa Ku Karhala ka ku Velekela',
    q_of: 'Swivutiso {n} swa 10', btn_next: 'Lexi landzelaka', btn_results: 'Vona swipfumelo swa mina', btn_back: 'Endzhaku',
    result_label: 'Ntlawa wa wena wa EPDS', result_means: 'Leswi swi vula yini', result_steps: 'Magoza lama ringanyetiweke lama landzelaka',
    result_btn_alert: 'Xivisa nhlangano wa mina wa pfuneto', result_btn_resources: 'Languta switirho swa pfuneto', result_btn_retake: 'Teka hlelo gape',
    result_categories: { low: 'Xivangelo lexintsongo', mid: 'Gare', high: 'Xivangelo lexikulu' },
    result_meanings: {
      low: 'Ntlawa wa wena a wu tlheli eka nkoka. Tshika ku hlola mimpfumawulo ya wena siku na siku.',
      mid: 'Ntlawa wa wena wu kombisa leswaku u nga va na swimelelo swa ku karhala ka ku velekela. Vulavula ni muhlayisi wa vulavulisi bya miri ku nga duri.',
      high: 'Ntlawa wa wena wu tlhela eka nkoka. Kombela u khalakata na muhlayisi wa vulavulisi bya miri namuntlha.'
    },
    result_steps_text: {
      low: 'Tshika ku hlola mimpfumawulo siku na siku. Avelana ntlawa wa wena ni muhlayisi wa vulavulisi bya miri.',
      mid: 'Vulavula ni xiphukuphuku xa vulavulisi bya miri emisukwini ya malokwana ya landzelaka.',
      high: 'Khalakata na muhlayisi wa vulavulisi bya miri namuntlha. Tirhisa batani ra Xiviselo.'
    },
    resources_title: 'Switirho swa Pfuneto', resources_sub: 'Swi kumeka handle ka inthanete',
    res_tabs: ['Twisisa PPD', 'Switirho', 'Ndyangu & Xikaya', 'Tinomboro ta Pfuneto', 'Vulavulisi bya Miri'],
    alert_screen_title: 'Xivisa nhlangano wa mina wa pfuneto', alert_screen_sub: 'Rhumela mhaka eka muhlayisi wa vulavulisi bya miri kumbe munhu wo rhandza',
    send_btn: 'Rhumela xiviselo sweswi', send_hint: 'Yi tirha handle ka inthanete hi SMS',
    default_message: 'Ndzi na swiphiqo swa impilo ya mina ya muanakanyo sweswi. Kombela u languta hina. — Yi rhumeleriwe ku tswa eka Mama Minds',
    profile_title: 'Profayili ya mina', plan_label: 'Mupfumelelo wa sweswi', plan_free: 'Asisekelo (Mahala)',
    language_label: 'Ririmi', location_label: 'Ndhawu', offline_label: 'Nhlayo ya ku se ri na inthanete',
    last_assess_label: 'Hlelo ra makumu', delete_data: 'Susa data ya mina',
    upgrade_title: 'Mama Minds Plus',
    upgrade_desc: 'Hlelo leri nga heriki, ku bukhisa sesene ra tele-miri. R89/tin\'weti kumbe R799/lembe.',
    upgrade_btn: 'Engetela eka Plus'
  },

  ve: {
    name: 'Tshivenḓa', chip: 'VE', native: 'Tshivenḓa',
    greeting: 'Ndaa,', offline: 'I shuma nga nnḓa ha inthanete',
    checkin_label: 'Maḓuvha u bva tshikolo tshau tsha u fhedzela', checkin_hint: 'Thatha u ṱoḓulusa mafaro au a ḽino ḓuvha',
    alert_title: 'Taledza nḓivhadzo yau ya u thusa', alert_sub: 'Swika kha mushumisi wa mapfurelo kana munna wavho wo fiwaho',
    mood_label: 'No livhana hani ḽino ḓuvha?',
    tools_label: 'Zwipiḓa na u thusa', progress_label: 'Mbuyelo wa tshifhinga', last_score: 'Pointe yau ya EPDS ya u fhedzela',
    card_assess: 'Ṱoḓuluso ya EPDS', card_assess_sub: 'Mbudziso dza 10',
    card_resources: 'Zwithu', card_resources_sub: 'Dzimbiisano & u thusa',
    card_help: 'Wana thuso zwino', card_help_sub: 'Taledza u thusa',
    card_profile: 'Profhaele yanga', card_profile_sub: 'Zwilaedza & ṱhogomelo',
    moods: ['Fhasi', 'Zwi luga', 'Zwavhudi', 'A tshega'],
    nav: ['Hayani', 'Sedzela', 'Zwithu', 'Taledza'],
    assess_title: 'Ṱoḓuluso ya EPDS', assess_sub: 'Tekanyo ya Edinburgh ya u Hluwa nga murahu ha u Bebelesa',
    q_of: 'Mbudziso {n} ya 10', btn_next: 'Ine ya tevhela', btn_results: 'Vhona mvelelo dzanga', btn_back: 'Murahu',
    result_label: 'Pointe yau ya EPDS', result_means: 'Zwine zwa amba mini', result_steps: 'Nḓila dzo humbulwaho dza u tevhela',
    result_btn_alert: 'Taledza nḓivhadzo yanga ya u thusa', result_btn_resources: 'Vhona zwithu zwa u thusa', result_btn_retake: 'Thatha ṱoḓuluso hafhu',
    result_categories: { low: 'Tshiphiri tshithukhu', mid: 'Gare', high: 'Tshiphiri tshihulwane' },
    result_meanings: {
      low: 'Pointe yau a yo phagami. Ṱoḓa u sedzela mafaro au ḽiṅwe na ḽiṅwe ḓuvha.',
      mid: 'Pointe yau i sumbedza uri u nga vha na zwiṅwe zwa u hluwa nga murahu ha u bebelesa. Amba na mushumisi wa mapfurelo.',
      high: 'Pointe yau yo phagama. Nga kha ḓi kwama mushumisi wa mapfurelo ḽino ḓuvha.'
    },
    result_steps_text: {
      low: 'Ṱoḓa u sedzela mafaro ḽiṅwe na ḽiṅwe ḓuvha. Kovhekanya pointe yau na mushumisi wa mapfurelo.',
      mid: 'Amba na mudzidzisi wa mapfurelo maḓuvha maṅwe na maṅwe a u tevhela.',
      high: 'Kwama mushumisi wa mapfurelo ḽino ḓuvha. Shumisa konopo ya Taleḓza.'
    },
    resources_title: 'Zwithu zwa u Thusa', resources_sub: 'Zwi wanala nga nnḓa ha inthanete',
    res_tabs: ['Pfesesa PPD', 'Zwipiḓa', 'Muṱa & Lushaka', 'Tshivhalo tsha Thuso', 'Ṱhogomelo ya Mapfurelo'],
    alert_screen_title: 'Taledza nḓivhadzo yanga ya u thusa', alert_screen_sub: 'Ruma mafhungo kha mushumisi wa mapfurelo kana munna wavho wo fiwaho',
    send_btn: 'Ruma nḓivhadzo zwino', send_hint: 'I shuma nga nnḓa ha inthanete nga SMS',
    default_message: 'Ndi na vhuṱungu ha ndeme yanga ya muṱambo zwino. Nga kha ḓi nṱuwa kha ine nda vha yone. — I rumwaho u bva kha Mama Minds',
    profile_title: 'Profhaele yanga', plan_label: 'Ṱhogomelo ya zwino', plan_free: 'Ḓa u Thoma (Mahala)',
    language_label: 'Luambo', location_label: 'Fhethu', offline_label: 'Nḓila ya u songo vha na inthanete',
    last_assess_label: 'Ṱoḓuluso ya u fhedzela', delete_data: 'Dzima data yanga',
    upgrade_title: 'Mama Minds Plus',
    upgrade_desc: 'Ṱoḓuluso yo nṱhesa, u bukhisa sesene ya tele-mapfurelo. R89/phando kana R799/ṅwaha.',
    upgrade_btn: 'Engedza kha Plus'
  },

  ss: {
    name: 'siSwati', chip: 'SS', native: 'siSwati',
    greeting: 'Sawubona,', offline: 'Isebenta ngaphandle kwe-inthaneti',
    checkin_label: 'Emalanga kusukela ekulingweni kwakho kwekugcina', checkin_hint: 'Tsatsa uhlolo lwemizwa yakho lamuhla',
    alert_title: 'Tsebisa inethiwekhi yakho yekusekela', alert_sub: 'Finyelela mosebenti wemphilo noma umuntfu lothandwako',
    mood_label: 'Uzizwa njani lamuhla?',
    tools_label: 'Ticiniselo nelusito', progress_label: 'Kuhamba phambili kwamanje', last_score: 'Amapointe akho e-EPDS ekugcina',
    card_assess: 'Uhlolisiselo lwe-EPDS', card_assess_sub: 'Imibuzo lelishumi',
    card_resources: 'Ticonco', card_resources_sub: 'Tikhokelo nelusito',
    card_help: 'Tsatsa lusito manje', card_help_sub: 'Tsebisa lusito',
    card_profile: 'Iphrofayili yami', card_profile_sub: 'Tilungiselelo nesicelo',
    moods: ['Phansi', 'Kulungile', 'Kahle', 'Ujabule'],
    nav: ['Ekhaya', 'Hlola', 'Ticonco', 'Tsebisa'],
    assess_title: 'Uhlolisiselo lwe-EPDS', assess_sub: 'Silinganiso se-Edinburgh sekudzabuka ngemuva kwekubelethwa',
    q_of: 'Umbuzo {n} we-10', btn_next: 'Lokulandelako', btn_results: 'Bona imiphumela yami', btn_back: 'Emuva',
    result_label: 'Amapointe akho e-EPDS', result_means: 'Lokhu kusho yini', result_steps: 'Tigaba letinconyiwe letilandelako',
    result_btn_alert: 'Tsebisa inethiwekhi yami yekusekela', result_btn_resources: 'Buka ticonco tekusekela', result_btn_retake: 'Tsatsa uhlolisiselo futsi',
    result_categories: { low: 'Ingoti lencinane', mid: 'Phakathi', high: 'Ingoti lenkhulu' },
    result_meanings: {
      low: 'Amapointe akho ase phansi. Tswela phambili ngokullandela imizwa yakho nsuku tonkhe.',
      mid: 'Amapointe akho abonisa kutsi ungase unematfambiselo ekudzabukeni ngemuva kwekubelethwa. Khuluma nalosebentela emaphelo.',
      high: 'Amapointe akho aphezulu. Sicela uxhumane nomhlinzeki wemphilo lamuhla.'
    },
    result_steps_text: {
      low: 'Tswela phambili ngokullandela imizwa nsuku tonkhe. Abelana namapointe akho nalosebentela emaphelo.',
      mid: 'Khuluma nangchwepheshe wemphilo emalangeni lambalwa lalandelako.',
      high: 'Xhumana nomhlinzeki wemphilo lamuhla. Sebentisa inkinobho yeTsebisa.'
    },
    resources_title: 'Ticonco Tekusekela', resources_sub: 'Iyatfolakala ngaphandle kwe-inthaneti',
    res_tabs: ['Ticondvo te-PPD', 'Ticiniselo', 'Umndeni & Umphakati', 'Tinombolo Telusito', 'Tindlela Tekuphilisa'],
    alert_screen_title: 'Tsebisa inethiwekhi yami yekusekela', alert_screen_sub: 'Thumela umyalezo kumhlinzeki wemphilo noma umuntfu lothandwako',
    send_btn: 'Thumela isaziso manje', send_hint: 'Isebenta ngaphandle kwe-inthaneti nge-SMS',
    default_message: 'Ngibambe ematfungulo empilo yami yemcondvo njalo. Sicela ujonge ngami. — Kuthunywe ku-Mama Minds',
    profile_title: 'Iphrofayili yami', plan_label: 'Isicelo samanje', plan_free: 'Isisekelo (Simahla)',
    language_label: 'Lulwimi', location_label: 'Indzawo', offline_label: 'Imodi yekungabi ne-inthaneti',
    last_assess_label: 'Uhlolisiselo lwekugcina', delete_data: 'Susa idatha yami',
    upgrade_title: 'Mama Minds Plus',
    upgrade_desc: 'Uhlolisiselo olungakhawuliwe, ukubhukha ithele-mpilo, ingxoxo yomhleli wengqondo. R89/inyanga noma R799/unyaka.',
    upgrade_btn: 'Khushulelana ku-Plus'
  },

  nr: {
    name: 'isiNdebele', chip: 'NR', native: 'isiNdebele',
    greeting: 'Lotjha,', offline: 'Isebenza ngaphandle kwe-inthanethi',
    checkin_label: 'Iintsuku kusukela ekulingweni kwakho kwegcina', checkin_hint: 'Thabatha uhlolo lwemizwelo yakho lamhlanje',
    alert_title: 'Xwayisa inethiwekhi yakho yekusekelwa', alert_sub: 'Fikelela umsizi wezempilo noma umuntu omthandako',
    mood_label: 'Uzizwa njani lamhlanje?',
    tools_label: 'Izinqopho nokusekela', progress_label: 'Intlhatlheko yakamuva', last_score: 'Amazinga wakho we-EPDS wakamuva',
    card_assess: 'Uhlolisiselo lwe-EPDS', card_assess_sub: 'Imibuzo elishumi',
    card_resources: 'Izinsiza', card_resources_sub: 'Izikhungo nokusekela',
    card_help: 'Thola usizo manje', card_help_sub: 'Xwayisa ukusekela',
    card_profile: 'Iprofayele yami', card_profile_sub: 'Izitatimende nehlelo',
    moods: ['Phansi', 'Kulungile', 'Kahle', 'Ujabule'],
    nav: ['Ikhaya', 'Bheka', 'Izinsiza', 'Xwayisa'],
    assess_title: 'Uhlolisiselo lwe-EPDS', assess_sub: 'Isilinganiso se-Edinburgh Sokudabuka Ngemuva Kokuzala',
    q_of: 'Umbuzo {n} we-10', btn_next: 'Okulandelayo', btn_results: 'Bona imiphumela yami', btn_back: 'Emuva',
    result_label: 'Amazinga wakho we-EPDS', result_means: 'Lokhu kusho ukuthini', result_steps: 'Izinyathelo ezinconyiwe ezilandelayo',
    result_btn_alert: 'Xwayisa inethiwekhi yami yokusekela', result_btn_resources: 'Buka izinsiza zokusekela', result_btn_retake: 'Phinda ukuhlolwa',
    result_categories: { low: 'Ubungozi obanso', mid: 'Phakathi', high: 'Ubungozi obukhulu' },
    result_meanings: {
      low: 'Amazinga wakho ase phansi. Qhubeka nokulandelela imizwelo nsuku zonke.',
      mid: 'Amazinga wakho abonisa ukuthi ungase ube nezimpawu zokudabuka ngemuva kokuzala. Khuluma nochwepheshe wezempilo maduze.',
      high: 'Amazinga wakho aphezulu. Sicela uxhumane nomhlinzeki wezempilo lamhlanje.'
    },
    result_steps_text: {
      low: 'Qhubeka nokulandelela imizwelo nsuku zonke. Yabelana namazinga nakho nomsizi wezempilo.',
      mid: 'Khuluma nochwepheshe wezempilo ezinsukwini ezimbalwa.',
      high: 'Xhumana nomhlinzeki wezempilo lamhlanje. Sebenzisa inkinobho Yexwayiso.'
    },
    resources_title: 'Izinsiza Zokusekela', resources_sub: 'Iyatholakala ngaphandle kwe-inthanethi',
    res_tabs: ['Qonda i-PPD', 'Izinqopho', 'Umndeni & Umphakathi', 'Izinombolo Zosizo', 'Ezempilo'],
    alert_screen_title: 'Xwayisa inethiwekhi yami yokusekela', alert_screen_sub: 'Thumela umyalezo kumhlinzeki wezempilo noma umuntu omthandako',
    send_btn: 'Thumela isixwayiso manje', send_hint: 'Isebenza ngaphandle kwe-inthanethi nge-SMS',
    default_message: 'Ngikhathazekile ngezempilo yami yengqondo njengamanje. Ngicela uhlole ukuthi nginjani. — Kuthunywe ku-Mama Minds',
    profile_title: 'Iprofayele yami', plan_label: 'Ihlelo lamanje', plan_free: 'Isisekelo (Simahla)',
    language_label: 'Ulimi', location_label: 'Indawo', offline_label: 'Imodi yokukhona ngaphandle kwe-inthanethi',
    last_assess_label: 'Ukuhlolwa okokugcina', delete_data: 'Susa idatha yami',
    upgrade_title: 'Mama Minds Plus',
    upgrade_desc: 'Ukuhlolwa okungakhawuliwe, ukubhukha ithele-mpilo, ingxoxo yomhleli wezengqondo. R89/inyanga noma R799/unyaka.',
    upgrade_btn: 'Khushulelana ku-Plus'
  }
};

export const DEFAULT_LANG = 'en';
